"use client";

import { useState } from "react";

const personas = {
  Teacher: {
    icon: "▤", title: "Get your Sundays back.",
    points: ["Build a full question paper from a blueprint in minutes, not evenings.","Generate the answer key and marking scheme together, then approve both before anyone sees a mark.","Upload answer scripts. AI applies your approved scheme, including step marks and partial credit.","Change a step mark and regrade the whole set in one click.","You are the final authority on every single mark. Always."],
  },
  "Principal & Academic Head": {
    icon: "▦", title: "Stop discovering problems in March.",
    points: ["Concept-level heatmaps across every section and subject, updated after every assessment.","See prerequisite gaps carrying forward between classes while there is still time to act.","Intervention groups form per concept and dissolve when the concept is fixed. No permanent label.","Keep an evidence trail for moderation, PTM and inspection.","Compare intended teaching with demonstrated learning - the competency gap schools need to close."],
  },
  "School Owner & Chain": {
    icon: "⌘", title: "Learning improvement you can show a parent.",
    points: ["Every PTM can end with a teacher-approved concept report and a 30-day plan for that child.","Show parents what their child does not yet understand - and the plan to address it.","Reassessment evidence shows whether the intervention worked.","Use the papers and answer scripts your school already produces. No new hardware or curriculum change.","Deploy branch by branch with one academic standard across the network."],
  },
} as const;

const concepts = ["Atoms & molecules","Mole ratio","Balancing","Mass conservation","Limiting reagent","Unit conversion","Formula writing","Valency","Reaction types","Stoichiometry","Yield","Scientific notation"];
const students = ["AS","RK","PM","NV","SK","AD","TM","RJ"];
const heat = [2,2,1,2,1,2,2,1, 2,0,1,0,0,1,0,1, 2,2,2,1,2,2,1,2, 1,0,1,0,1,0,0,1, 0,0,1,0,0,1,0,0, 2,1,2,1,2,1,1,2, 2,2,1,2,2,1,2,1, 2,1,1,2,1,2,1,1, 1,1,2,1,1,2,1,1, 1,0,1,0,1,0,0,1, 2,1,2,2,1,2,2,1, 2,2,1,2,2,1,2,2];

const stages = [
  ["Set","Choose outcomes, difficulty, cognitive level, question types and marks. Paper, key and rubric generate together.","Teacher approves"],
  ["Check","Upload tests, homework or assignments. AI applies the approved scheme with step and partial marks.","Teacher approves"],
  ["See","Class and student heatmaps surface concept understanding, prerequisites and misconceptions.","Evidence linked"],
  ["Act","Create temporary intervention groups and personalised practice for regular or remedial periods.","Teacher assigns"],
  ["Prove","Reassess the same concepts and show whether understanding actually moved.","Improvement verified"],
];

export default function MarketingHome(){
  const [persona,setPersona]=useState<keyof typeof personas>("Teacher");
  const [reveal,setReveal]=useState(52);
  const active=personas[persona];
  return <main className="mkt">
    <nav className="mkt-nav"><a className="mkt-brand" href="#top"><img src="/brand/logo.png" alt="EduAI Hub"/><span><b>Learning X-Ray</b><small>EduIntelligence Hubs Pvt. Ltd.</small></span></a><div><a href="#how">How it works</a><a href="#safety">Safety</a><a href="#faq">FAQ</a><a className="nav-signin" href="/signin">Sign in</a></div></nav>

    <section className="mkt-hero" id="top"><div className="hero-copy"><p className="mkt-eyebrow">EduAI Hub · Learning X-Ray</p><h1>Marks tell you who scored. Learning X-Ray tells you why.</h1><p className="hero-lead">Teacher-approved AI that sets the paper, checks the work, maps every concept gap in your class, and generates the exact practice each child needs - then reassesses to prove the gap actually closed.</p><div className="trust-strip"><span>✓ Teacher approves every mark</span><span>○ No rankings. No labels.</span><span>◆ Built for Indian school boards</span></div><div className="hero-actions"><a className="mkt-primary" href="/signin">Run a free X-Ray on your last class test</a><a className="mkt-link" href="#heatmap">See a sample Class 9 heatmap →</a></div><p className="micro">Upload a test you have already conducted. Get the class heatmap and one personalised worksheet back. No setup, no integration, no cost.</p></div><XrayReveal value={reveal} setValue={setReveal}/></section>

    <section className="explainer"><p className="mkt-eyebrow">The five-second explainer</p><h2>A blood test tells you what a thermometer can't.</h2><div><p>A mark sheet says a child scored 62%. It does not say the child understands balancing equations but cannot read a mole ratio. One number hides thirty different reasons.</p><p>Learning X-Ray reads the same answer scripts your teachers already correct and returns the reasons - concept by concept, child by child - with the practice material to fix each one.</p></div></section>

    <section className="mkt-section personas"><header><p className="mkt-eyebrow">Built around the outcome you own</p><h2>Three people. One platform. Three different problems solved.</h2></header><div className="persona-tabs" role="tablist">{(Object.keys(personas) as (keyof typeof personas)[]).map(p=><button key={p} role="tab" aria-selected={persona===p} onClick={()=>setPersona(p)}><i>{personas[p].icon}</i>{p}</button>)}</div><article className="persona-panel"><div><p>For {persona}</p><h3>{active.title}</h3></div><ul>{active.points.map(x=><li key={x}>{x}</li>)}</ul></article></section>

    <section className="mkt-section heat-section" id="heatmap"><header><p className="mkt-eyebrow">Illustrative, anonymised Class 9 Science view</p><h2>One class. Twelve concepts. The pattern becomes visible.</h2></header><div className="heat-layout"><div className="heat-card"><div className="heat-key"><span className="secure">Secure</span><span className="partial">Partial</span><span className="gap">Needs attention</span></div><div className="mkt-heat" style={{gridTemplateColumns:`160px repeat(${students.length},1fr)`}}><i/>{students.map(s=><b key={s}>{s}</b>)}{concepts.flatMap((c,r)=>[<strong key={c}>{c}</strong>,...students.map((s,i)=><button key={c+s} className={["gap","partial","secure"][heat[r*students.length+i]]} title={`${s} · ${c} · ${["Needs attention","Partial","Secure"][heat[r*students.length+i]]}`}/>)])}</div></div><aside><p><b>01</b>Nine students missed the same prerequisite from the previous class.</p><p><b>02</b>This is a concept problem, not a chapter problem.</p><p><b>03</b>Group formed for this concept only. Dissolves on reassessment.</p></aside></div></section>

    <section className="mkt-section" id="how"><header><p className="mkt-eyebrow">How it works</p><h2>From blank paper to proven improvement.</h2></header><div className="stage-cycle">{stages.map((s,i)=><article key={s[0]} className={i===4?"prove":""}><span>{i+1}</span><h3>{s[0]}</h3><p>{s[1]}</p><b>{s[2]}</b></article>)}</div><p className="closing-line">Most platforms stop at Stage 3. Stage 5 is the one that changes a board result.</p></section>

    <section className="mkt-section authority"><header><p className="mkt-eyebrow">Teacher authority</p><h2>What Learning X-Ray will never do.</h2></header><div className="authority-table"><div className="authority-head"><b>Never</b><b>Always</b></div>{[["Publish a mark you have not approved","Hold every AI mark as a draft until you sign off"],["Rank students against each other","Report each child against the concept, not the class"],["Label a child weak or slow","Group by concept temporarily, then dissolve the group"],["Report teacher performance to management","Report learning gaps so teaching can be supported"],["Replace professional judgement","Show the evidence behind every suggestion"]].map(r=><div key={r[0]}><span>{r[0]}</span><span>{r[1]}</span></div>)}</div></section>

    <section className="mkt-section founding"><div><p className="mkt-eyebrow">Evidence, not adjectives</p><h2>Be one of the first ten.</h2><p>We are running Learning X-Ray with ten schools, free, for 15 days - 2 classes, 2 teachers and up to 100 students per school. You keep every report generated. We publish results only with your permission.</p><a className="mkt-primary" href="mailto:contact@eduaihub.in?subject=Learning%20X-Ray%20founding%20cohort">Apply for the founding cohort</a></div><ParentPhone/></section>

    <section className="mkt-section works"><header><p className="mkt-eyebrow">Fits the school you already run</p><h2>No new hardware. No new curriculum. No new textbook.</h2></header><div className="feature-grid">{["Your existing question papers and answer scripts","Handwritten work with mandatory teacher validation of extracted text","Your marking scheme and moderation rules","CBSE, ICSE and State-board assessment patterns","Teacher-approved reports ready for school workflows","Secure access by role and section"].map((x,i)=><article key={x}><span>0{i+1}</span><p>{x}</p></article>)}</div></section>

    <section className="mkt-section safety" id="safety"><div><p className="mkt-eyebrow">Data & child safety</p><h2>Student data stays under school control.</h2><p>Teachers see their sections, Principals see the school, and parents see only their own child's approved report. Every mark and regrade keeps an audit trail. Ask us for the current data-processing, hosting and retention documentation during your review.</p></div><div className="safety-seal"><span>✓</span><b>Teacher-approved</b><small>Role-based access · audit history · secure parent sharing</small></div></section>

    <section className="mkt-section rollout"><header><p className="mkt-eyebrow">Rollout</p><h2>Six weeks from first upload to proven improvement.</h2></header><div className="timeline">{[["1","Onboard two teachers and upload one existing test.","90 min"],["2","Review the first heatmap with the academic head.","1 meeting"],["3–4","Assign practice and run intervention in normal periods.","Existing timetable"],["5","Reassess the same concepts.","1 period"],["6","Share improvement and PTM reports.","As scheduled"]].map(w=><article key={w[0]}><b>Week {w[0]}</b><p>{w[1]}</p><span>{w[2]}</span></article>)}</div></section>

    <section className="mkt-section pricing"><div><p className="mkt-eyebrow">Simple commercial model</p><h2>Priced per classroom, not per feature.</h2><p>One annual classroom licence. Blueprint, grading, heatmaps, practice generation, reassessment and reports are included. Multi-branch pricing and year-one onboarding are available.</p></div><a className="mkt-primary light" href="mailto:contact@eduaihub.in?subject=Learning%20X-Ray%20costing">Get a costing for your school</a></section>

    <section className="mkt-section faq" id="faq"><header><p className="mkt-eyebrow">Frequently asked questions</p><h2>Straight answers before you pilot.</h2></header>{[["Does the AI decide my students' marks?","No. It applies the marking scheme you approved and produces a draft. Nothing is final until the teacher confirms it."],["Will this be used to evaluate teachers?","No. Learning X-Ray reports concept gaps, not teacher performance. The purpose is to support teaching, not score it."],["Does it work with handwritten answer scripts?","It can extract text from clear scanned handwriting, but results vary with legibility, scan quality, language, diagrams and subject notation. Teachers must review and correct the extracted text before analysis."],["What if a teacher disagrees with the grading?","The teacher overrides it. The override is recorded, and the same correction can be applied across the set."],["How much extra work is this?","The aim is less work: paper setting and checking get faster, while diagnosis and practice material are generated for review."],["Do children get labelled as weak?","No. Groups are tied to one concept and dissolve when that concept is fixed. There is no permanent student tag."]].map(q=><details key={q[0]}><summary>{q[0]}<span>+</span></summary><p>{q[1]}</p></details>)}</section>

    <section className="final-cta"><p className="mkt-eyebrow">Start with work your teachers already have</p><h2>You already have the answer scripts. Let's read them properly.</h2><div><a className="mkt-primary" href="/signin">Run a free X-Ray on your last class test</a><a className="mkt-secondary" href="mailto:contact@eduaihub.in?subject=Learning%20X-Ray%20conversation">Talk to us for 20 minutes</a></div><a className="final-signin" href="/signin">Already a school on Learning X-Ray? Sign in →</a></section>
    <footer className="mkt-footer"><img src="/brand/logo.png" alt="EduAI Hub"/><span>EduIntelligence Hubs Pvt. Ltd. · Chandigarh, India</span><nav><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="mailto:contact@eduaihub.in">Contact</a></nav></footer>
  </main>;
}

function XrayReveal({value,setValue}:{value:number;setValue:(n:number)=>void}){return <div className="xray-reveal" aria-label="The same answer script shown first as one mark, then as concept-level evidence"><div className="answer-script"><div className="paper-top"><b>Class 9 · Science</b><span>62/100</span></div><p>Q4. Calculate the limiting reagent and show the mole ratio.</p><em>2H₂ + O₂ → 2H₂O</em><p className="handwriting">The ratio is 2:1. Oxygen will finish first because...</p><p>Q5. Balance the equation and include units.</p><em>Fe + O₂ → Fe₂O₃</em><p className="handwriting">4Fe + 3O₂ → 2Fe₂O₃</p></div><div className="scan-side" style={{clipPath:`inset(0 0 0 ${value}%)`}}><div className="scan-line" style={{left:`${value}%`}}/><span className="tag gap-tag" style={{top:"26%",left:"54%"}}>Mole ratio · gap</span><span className="tag secure-tag" style={{top:"44%",left:"59%"}}>Balancing · secure</span><span className="tag gap-tag" style={{top:"61%",left:"47%"}}>Limiting reagent · gap</span><span className="tag secure-tag" style={{top:"76%",left:"61%"}}>Unit conversion · secure</span></div><input aria-label="Reveal concept-level X-Ray" type="range" min="18" max="82" value={value} onChange={e=>setValue(Number(e.target.value))}/><div className="slider-handle" style={{left:`${value}%`}}>↔</div></div>}

function ParentPhone(){return <div className="phone"><div className="phone-bar"><i/>Parent view <b>▦</b></div><div className="phone-body"><small>Approved for</small><h3>Aarav's 30-day plan</h3><div className="parent-score"><b>3</b><span>concepts secure</span><b>2</b><span>to work on</span></div><ol><li><b>Week 1</b>Mole ratio practice</li><li><b>Week 2</b>Guided examples</li><li><b>Week 4</b>Reassessment</li></ol><p>Approved by Asha Sharma<br/>31 July 2026</p></div></div>}
