# Generated by Django 5.2.17 on 2026-09-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('school_id', models.TextField()),
                ('actor_id', models.TextField(blank=True, null=True)),
                ('action', models.TextField()),
                ('entity_type', models.TextField()),
                ('entity_id', models.TextField(blank=True, null=True)),
                ('detail_json', models.JSONField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'audit_events',
                'managed': False,
            },
        ),
    ]
