# Generated by Django 5.2.17 on 2026-09-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('city', models.TextField(blank=True, null=True)),
                ('board', models.TextField(blank=True, null=True)),
                ('settings_json', models.JSONField()),
                ('status', models.TextField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Suspended', 'Suspended'), ('Closed', 'Closed')])),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'schools',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('academic_year', models.TextField()),
                ('class_name', models.TextField()),
                ('section', models.TextField()),
                ('subject', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('roll_number', models.TextField(blank=True, null=True)),
                ('status', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupportAccessGrant',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'support_access_grants',
                'managed': False,
            },
        ),
    ]
