import { getAuthorizedProfile } from "../../../../lib/authorization";
import { getSupabaseServer } from "../../../../lib/supabase-server";

const kinds=["group_project","problem_inquiry","classroom_interaction","online_course","community_skill"];
const grouped=(items:any[])=>{const result=new Map<string,any[]>();for(const item of items||[])result.set(item.applied_learning_record_id,[...(result.get(item.applied_learning_record_id)||[]),item]);return result};
const one=(items:any[])=>new Map((items||[]).map(item=>[item.applied_learning_record_id,item]));

export async function GET(request:Request){
  const profile=await getAuthorizedProfile(request);if(profile instanceof Response)return profile;const learnerId=new URL(request.url).searchParams.get("learnerId")||"",db=getSupabaseServer();
  const {data:learner}=await db.from("hpc_learner_profiles").select("id,grade").eq("id",learnerId).eq("school_id",profile.school_id).maybeSingle();if(!learner)return Response.json({error:"Learner not found."},{status:404});if(Number(learner.grade)<9)return Response.json({error:"Applied-learning records are available only for Secondary-stage learners."},{status:403});
  const {data,error}=await db.from("hpc_applied_learning_records").select("*").eq("learner_profile_id",learner.id).order("created_at",{ascending:false});if(error)return Response.json({error:error.message},{status:500});const ids=(data||[]).map(item=>item.id);
  const [stages,mappings,criteria,assessments,proofs,milestones,barriers]=ids.length?await Promise.all([
    db.from("hpc_applied_learning_stage_reviews").select("*").in("applied_learning_record_id",ids).order("stage_number"),db.from("hpc_applied_learning_mappings").select("*,hpc_domains(label),hpc_curricular_goals(code,label),hpc_competencies(code,label),hpc_learning_outcomes(code,label),hpc_abilities(label)").in("applied_learning_record_id",ids),db.from("hpc_applied_learning_rubric_criteria").select("*").in("applied_learning_record_id",ids),db.from("hpc_applied_learning_final_assessments").select("*").in("applied_learning_record_id",ids),db.from("hpc_applied_learning_course_proofs").select("*").in("applied_learning_record_id",ids),db.from("hpc_applied_learning_milestones").select("*").in("applied_learning_record_id",ids).order("due_date"),db.from("hpc_applied_learning_barriers").select("*").in("applied_learning_record_id",ids).order("created_at",{ascending:false}),
  ]):[{data:[]},{data:[]},{data:[]},{data:[]},{data:[]},{data:[]},{data:[]}];
  const byStages=grouped(stages.data||[]),byMappings=grouped(mappings.data||[]),byCriteria=grouped(criteria.data||[]),byMilestones=grouped(milestones.data||[]),byBarriers=grouped(barriers.data||[]),byAssessments=one(assessments.data||[]),byProofs=one(proofs.data||[]);
  return Response.json({records:(data||[]).map(item=>({...item,stages:byStages.get(item.id)||[],mappings:byMappings.get(item.id)||[],criteria:byCriteria.get(item.id)||[],finalAssessment:byAssessments.get(item.id)||null,courseProof:byProofs.get(item.id)||null,milestones:byMilestones.get(item.id)||[],barriers:byBarriers.get(item.id)||[]}))});
}

export async function POST(request:Request){
  const profile=await getAuthorizedProfile(request);if(profile instanceof Response)return profile;const body=await request.json() as Record<string,unknown>,learnerId=String(body.learnerId||""),type=String(body.recordType||""),title=String(body.title||"").trim();if(!kinds.includes(type)||title.length<3)return Response.json({error:"Choose a record type and enter a title."},{status:400});const db=getSupabaseServer();
  const [{data:learner},{data:framework}]=await Promise.all([db.from("hpc_learner_profiles").select("id,grade,academic_year").eq("id",learnerId).eq("school_id",profile.school_id).maybeSingle(),db.from("hpc_framework_versions").select("id").eq("status","approved").eq("framework_code","PARAKH_HPC_SECONDARY").maybeSingle()]);if(!learner||Number(learner.grade)<9)return Response.json({error:"Only Secondary-stage learners can receive this record."},{status:403});if(!framework)return Response.json({error:"The approved Secondary-stage PARAKH framework package has not been loaded yet."},{status:400});
  const memberIds=[learner.id,...(Array.isArray(body.memberLearnerIds)?body.memberLearnerIds:[]).map(String)].filter((value,index,all)=>Boolean(value)&&all.indexOf(value)===index);if(type==="group_project"&&memberIds.length<2)return Response.json({error:"Choose at least one additional Secondary learner for a group project."},{status:400});const {data:members}=await db.from("hpc_learner_profiles").select("id,grade").in("id",memberIds).eq("school_id",profile.school_id);if((members||[]).length!==memberIds.length||(members||[]).some(item=>Number(item.grade)<9))return Response.json({error:"Group members must be Secondary learner profiles in your school."},{status:400});
  const prompt=String(body.promptText||"").trim(),reflection=String(body.learnerReflection||"").trim(),assessment=String(body.teacherAssessment||"").trim(),roles=String(body.roles||"").split(",").map(x=>x.trim()).filter(Boolean);
  const {data,error}=await db.from("hpc_applied_learning_records").insert({school_id:profile.school_id,learner_profile_id:learner.id,framework_version_id:framework.id,record_type:type,title,prompt_text:prompt||null,stage_number:Number(body.stageNumber)||null,interaction_type:String(body.interactionType||"").trim()||null,hours_spent:Number(body.hoursSpent)||null,completion_status:String(body.completionStatus||"planned"),term_label:String(body.termLabel||"").trim()||null,class_context:String(body.classContext||"").trim()||null,learner_reflection:reflection||null,teacher_assessment:assessment||null,peer_feedback:String(body.peerFeedback||"").trim()||null,teacher_comments:String(body.teacherComments||"").trim()||null,barriers_text:String(body.barriersText||"").trim()||null,schedule_json:{guiding_questions:String(body.guidingQuestions||"").trim()},roles_json:roles,rubric_json:{final_rubric:String(body.finalRubric||"").trim()},credits_json:{credits:Number(body.credits)||0},created_by:profile.id,updated_by:profile.id}).select("*").single();if(error)return Response.json({error:error.message},{status:500});
  const {error:memberError}=await db.from("hpc_applied_learning_members").insert(memberIds.map((id,index)=>({applied_learning_record_id:data.id,learner_profile_id:id,member_role:roles[index]||null})));if(memberError)return Response.json({error:`Record was saved, but its group members could not be linked: ${memberError.message}`},{status:500});const content=[title,prompt,assessment,reflection].filter(Boolean).join(" — ");const {data:evidence,error:evidenceError}=await db.from("hpc_evidence").insert({school_id:profile.school_id,learner_profile_id:learner.id,applied_learning_record_id:data.id,academic_year:learner.academic_year,framework_version_id:framework.id,source_type:"applied_learning",contributor_type:"teacher",contributor_user_id:profile.id,content,review_status:"teacher_review_required",sufficiency_status:"teacher_review_required"}).select("id,review_status").single();if(evidenceError)return Response.json({error:`Record was saved, but its evidence item could not be created: ${evidenceError.message}`},{status:500});return Response.json({record:data,evidence},{status:201});
}
