# Generated by Django 5.2.17 on 2026-09-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('invoice_number', models.TextField(unique=True)),
                ('billing_name', models.TextField()),
                ('billing_address', models.JSONField()),
                ('gstin', models.TextField(blank=True, null=True)),
                ('place_of_supply', models.TextField()),
                ('sac_code', models.TextField()),
                ('tax_rate_bps', models.IntegerField()),
                ('taxable_paise', models.BigIntegerField()),
                ('cgst_paise', models.BigIntegerField()),
                ('sgst_paise', models.BigIntegerField()),
                ('igst_paise', models.BigIntegerField()),
                ('total_paise', models.BigIntegerField()),
                ('invoice_date', models.DateField()),
                ('pdf_path', models.TextField(blank=True, null=True)),
                ('status', models.TextField(choices=[('issued', 'Issued'), ('cancelled', 'Cancelled')])),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'invoices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceCounter',
            fields=[
                ('financial_year', models.TextField(primary_key=True, serialize=False)),
                ('last_number', models.BigIntegerField()),
            ],
            options={
                'db_table': 'invoice_counters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('purpose', models.TextField(choices=[('subscription', 'New subscription'), ('subscription_renewal', 'Renewal'), ('credit_topup', 'Credit top-up')])),
                ('amount_paise', models.BigIntegerField()),
                ('tax_paise', models.BigIntegerField()),
                ('total_paise', models.BigIntegerField()),
                ('currency', models.TextField()),
                ('status', models.TextField(choices=[('created', 'Created'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially refunded')])),
                ('gateway', models.TextField()),
                ('gateway_order_id', models.TextField(blank=True, null=True)),
                ('gateway_payment_id', models.TextField(blank=True, null=True)),
                ('method', models.TextField(blank=True, null=True)),
                ('failure_code', models.TextField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('idempotency_key', models.TextField(unique=True)),
                ('notes', models.JSONField()),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('gateway', models.TextField()),
                ('gateway_event_id', models.TextField()),
                ('event_type', models.TextField()),
                ('signature_verified', models.BooleanField()),
                ('payload', models.JSONField()),
                ('status', models.TextField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')])),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('audience', models.TextField(choices=[('school', 'School (B2B)'), ('parent', 'Parent (B2C)')])),
                ('billing_period', models.TextField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('one_time', 'One time')])),
                ('amount_paise', models.BigIntegerField()),
                ('currency', models.TextField()),
                ('credits_included', models.IntegerField()),
                ('max_teachers', models.IntegerField(blank=True, null=True)),
                ('max_students', models.IntegerField(blank=True, null=True)),
                ('features', models.JSONField()),
                ('gateway', models.TextField(blank=True, null=True)),
                ('gateway_plan_id', models.TextField(blank=True, null=True)),
                ('status', models.TextField(choices=[('active', 'Active'), ('archived', 'Archived')])),
                ('sort_order', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'plans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.TextField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('grace', 'In grace period'), ('cancelled', 'Cancelled'), ('expired', 'Expired')])),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('grace_until', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField()),
                ('gateway', models.TextField()),
                ('gateway_subscription_id', models.TextField(blank=True, null=True)),
                ('gateway_customer_id', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'subscriptions',
                'managed': False,
            },
        ),
    ]
