"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";

type Role = "Teacher" | "Principal" | "School admin" | "Platform admin";
type View = "Home" | "Work" | "Review" | "X-Ray" | "Interventions" | "Reports" | "Admin";

const nav: Record<Role, View[]> = {
  Teacher: ["Home", "Work", "Review", "X-Ray", "Interventions", "Reports"],
  Principal: ["Home", "X-Ray", "Interventions", "Reports"],
  "School admin": ["Home", "Admin", "Reports"],
  "Platform admin": ["Home", "Admin", "Reports"],
};

const Icon = ({ name }: { name: View }) => <span className="nav-icon" aria-hidden>{({Home:"⌂",Work:"▣",Review:"✓", "X-Ray":"✦",Interventions:"↗",Reports:"▥",Admin:"⚙"} as Record<View,string>)[name]}</span>;

export default function EduAIApp({initialRole="Teacher"}:{initialRole?:Role}) {
  const [role, setRole] = useState<Role>(initialRole);
  const [view, setView] = useState<View>("Home");
  const [dark, setDark] = useState(false);
  const [toast, setToast] = useState("");
  const [reviewed, setReviewed] = useState(0);
  const [intervention, setIntervention] = useState(false);
  const [modal, setModal] = useState<"upload" | "create" | "report" | "invite" | null>(null);
  const [uploading, setUploading] = useState(false);
  const [uploaded, setUploaded] = useState(false);
  const [invites,setInvites]=useState<{name:string,email:string,role:string}[]>([]);

  useEffect(() => { document.documentElement.dataset.theme = dark ? "dark" : "light"; }, [dark]);
  useEffect(() => { if (!nav[role].includes(view)) setView("Home"); }, [role, view]);
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2600); };
  const title = useMemo(() => role === "Teacher" ? (view === "Home" ? "Good morning, Asha." : view) : role === "Principal" ? (view === "Home" ? "School academic improvement" : view) : role === "Platform admin" ? (view === "Home" ? "Platform overview" : view) : (view === "Home" ? "School administration" : view), [role, view]);

  return <div className="app-shell">
    <aside className="sidebar">
      <button className="brand" onClick={() => setView("Home")} aria-label="EduAI Learning X-Ray home">
        <img src="/brand/shield.png" alt="" /><span><b>Learning X-Ray</b><small>by EduAI Hub</small></span>
      </button>
      <nav aria-label="Primary navigation">{nav[role].map(item => <button key={item} data-testid={`nav-${item}`} className={view===item?"active":""} onClick={()=>setView(item)}><Icon name={item}/><span>{item}</span>{item==="Review" && reviewed<3 && <em>{3-reviewed}</em>}</button>)}</nav>
      <div className="sidebar-foot">
        <div className="privacy-note"><span>◉</span><div><b>Teacher approved</b><small>AI suggestions stay drafts</small></div></div>
        <button className="profile"><span>AS</span><div><b>Asha Sharma</b><small>Sunrise Academy</small></div><i>•••</i></button>
      </div>
    </aside>

    <main>
      <header className="topbar">
        <div className="mobile-brand"><img src="/brand/shield.png" alt="EduAI Hub"/><b>Learning X-Ray</b></div>
        <div className="crumb"><span>Sunrise Academy</span><i>›</i><b>Grade 6 · Mathematics</b></div>
        <div className="top-actions">
          <select aria-label="Switch role" value={role} onChange={e=>setRole(e.target.value as Role)}>{Object.keys(nav).map(r=><option key={r}>{r}</option>)}</select>
          <button aria-label="Toggle dark mode" onClick={()=>setDark(!dark)}>{dark?"☀":"☾"}</button>
          <button aria-label="Notifications" onClick={()=>notify("You have 2 notifications: one review reminder and one completed report")}>♢<em>2</em></button>
        </div>
      </header>
      <div className="content">
        <div className="page-heading"><div><p className="eyebrow">{role} workspace</p><h1>{title}</h1><p>{subtitle(role, view)}</p></div>{role==="Teacher"&&view==="Home"&&<button className="primary" onClick={()=>setModal("upload")}>＋ Upload work</button>}{view==="Reports"&&<button className="primary" onClick={()=>setModal("report")}>＋ Generate report</button>}</div>
        {role==="Teacher" && <TeacherView view={view} reviewed={reviewed} setReviewed={setReviewed} notify={notify} intervention={intervention} setIntervention={setIntervention} open={setModal}/>} 
        {role==="Principal" && <PrincipalView view={view} notify={notify}/>} 
        {role==="School admin" && <SchoolAdmin view={view} notify={notify} open={setModal} invites={invites}/>} 
        {role==="Platform admin" && <PlatformAdmin view={view} notify={notify}/>} 
      </div>
    </main>
    <nav className="mobile-nav" aria-label="Mobile navigation">{nav[role].slice(0,5).map(item=><button key={item} className={view===item?"active":""} onClick={()=>setView(item)}><Icon name={item}/><small>{item}</small></button>)}</nav>
    {toast && <div className="toast" role="status"><b>✓</b>{toast}</div>}
    {modal && <InteractionModal type={modal} close={()=>setModal(null)} notify={notify} uploading={uploading} uploaded={uploaded} addInvite={(invite:any)=>setInvites(items=>[...items,invite])} startUpload={()=>{setUploading(true);setTimeout(()=>{setUploading(false);setUploaded(true)},1400)}}/>}
  </div>;
}

function subtitle(role: Role, view: View) {
  if(role==="Teacher"&&view==="Home") return "Here’s the clearest path through today’s learning evidence.";
  if(role==="Principal") return "Aggregated, non-punitive insight for stronger academic support.";
  if(role==="Platform admin") return "Tenant health, responsible AI operations and platform performance.";
  if(role==="School admin") return "People, classes, privacy and school-wide configuration.";
  return ({Work:"Create, upload and follow every assessment from draft to analysis.",Review:"Teacher approval is required before marks or diagnoses are final.","X-Ray":"Concept mastery grounded in evidence, confidence and teacher judgement.",Interventions:"Turn priority gaps into practical support and follow-up.",Reports:"Secure, contextual reports with limitations made explicit.",Admin:"Manage configuration with tenant isolation and a complete audit trail.",Home:""} as Record<View,string>)[view];
}

function TeacherView({view,reviewed,setReviewed,notify,intervention,setIntervention,open}:any){
  if(view==="Home") return <>
    <section className="metric-grid five">
      <Metric tone="navy" label="Awaiting grading" value="84" note="3 assessments" action={()=>open("upload")}/><Metric tone="orange" label="Low confidence" value={String(3-reviewed)} note="Needs your judgement" action={()=>setReviewed(Math.min(3,reviewed+1))}/><Metric tone="red" label="Priority gaps" value="3" note="Across 2 concepts"/><Metric tone="green" label="Interventions due" value={intervention?"2":"3"} note="This week"/><Metric tone="purple" label="Follow-ups due" value="2" note="1 overdue"/>
    </section>
    <div className="dashboard-grid">
      <section className="card action-card"><div className="card-head"><div><p className="eyebrow">Recommended next</p><h2>Review three uncertain answers</h2></div><span className="status warning">8 min</span></div><p>AI found handwriting or reasoning that needs your judgement before marks are final.</p><div className="answer-stack"><div className="paper-lines"/><div><b>Fractions · Q3</b><p>“The denominator stays the same because…”</p><span className="confidence"><i/> Low confidence · handwriting</span></div></div><button className="primary" onClick={()=>setReviewed(Math.min(3,reviewed+1))}>{reviewed>=3?"All reviewed":"Review next answer"} <span>→</span></button></section>
      <section className="card"><div className="card-head"><div><p className="eyebrow">Class pulse</p><h2>Fractions needs attention</h2></div><button className="link" onClick={()=>notify("Opened the full Learning X-Ray")}>Open X-Ray →</button></div><div className="donut-row"><div className="donut"><span>64%<small>mastery</small></span></div><div className="legend"><p><i className="good"/> Demonstrated <b>12</b></p><p><i className="mid"/> Developing <b>8</b></p><p><i className="risk"/> Priority gap <b>6</b></p></div></div><div className="insight">✦ Students can find common denominators, but 6 need support adding unlike fractions.</div></section>
      <section className="card span-2"><div className="card-head"><div><p className="eyebrow">Your active work</p><h2>Keep the learning cycle moving</h2></div><button className="secondary" onClick={()=>open("create")}>＋ Create assessment</button></div><div className="table"><div className="tr th"><span>Assessment</span><span>Progress</span><span>Next step</span><span>Status</span></div><Row name="Fractions checkpoint" sub="Grade 6A · 28 students" progress="24 / 28" action="Review 3 answers" status="Review"/><Row name="Decimals exit ticket" sub="Grade 6B · today" progress="30 / 30" action="Open X-Ray" status="Ready"/><Row name="Algebra homework" sub="Grade 7A · yesterday" progress="18 / 32" action="Continue upload" status="Processing"/></div></section>
    </div>
  </>;
  if(view==="Work") return <WorkView open={open} notify={notify}/>;
  if(view==="Review") return <ReviewView reviewed={reviewed} setReviewed={setReviewed} notify={notify}/>;
  if(view==="X-Ray") return <XRay notify={notify}/>;
  if(view==="Interventions") return <Interventions intervention={intervention} setIntervention={setIntervention} notify={notify}/>;
  return <Reports notify={notify}/>;
}

function WorkView({open,notify}:any){return <div className="dashboard-grid"><section className="card span-2"><div className="card-head"><div><p className="eyebrow">Assessment pipeline</p><h2>Work</h2></div><div className="button-row"><button className="secondary" onClick={()=>open("create")}>＋ Create</button><button className="primary" onClick={()=>open("upload")}>↑ Upload</button></div></div><div className="filters"><button className="active">All 8</button><button>Draft 2</button><button>Processing 1</button><button>Needs review 3</button><button>Complete 2</button></div><div className="work-grid"><WorkCard title="Fractions checkpoint" meta="Grade 6A · 28 students" pct={86} state="Needs review"/><WorkCard title="Decimals exit ticket" meta="Grade 6B · 30 students" pct={100} state="Ready for X-Ray"/><WorkCard title="Algebra homework" meta="Grade 7A · 32 students" pct={56} state="Processing"/><WorkCard title="Geometry quiz" meta="Grade 6A · Draft" pct={20} state="Awaiting setup"/></div></section><section className="card span-2"><div className="card-head"><div><p className="eyebrow">Assessment quality</p><h2>Build stronger evidence</h2></div><span className="status success">Suitable with limitations</span></div><div className="quality-bars"><Bar label="Concept coverage" pct={82}/><Bar label="Evidence sufficiency" pct={68}/><Bar label="Cognitive balance" pct={74}/></div><p className="insight">✦ Add one application-level question for stronger evidence on equivalent fractions.</p></section></div>}
function ReviewView({reviewed,setReviewed,notify}:any){const done=reviewed>=3;return <div className="review-layout"><section className="card paper-panel"><div className="card-head"><div><p className="eyebrow">Original answer · Mira Bose</p><h2>Question 3 · Add unlike fractions</h2></div><span className="status warning">Low confidence</span></div><div className="paper"><p>2/3 + 1/4</p><p className="hand">= 3/7</p><p className="hand note">I added both top and bottom numbers.</p><i className="teacher-mark">?</i></div><div className="pager">← Previous <span>Answer {Math.min(reviewed+1,3)} of 3</span> Next →</div></section><aside className="card inspector"><p className="eyebrow">AI suggestion · draft</p><h2>0 / 2 marks</h2><div className="evidence"><b>Extracted answer</b><p>3/7 — student added denominators.</p></div><div className="evidence"><b>Expected evidence</b><p>Find a common denominator, convert both fractions, then add numerators.</p></div><div className="confidence-box"><span>Confidence</span><b>Low · 48%</b><small>Reason: ambiguous final digit and no working shown</small></div><label>Teacher mark<input defaultValue="0" aria-label="Teacher mark"/></label><label>Teacher note<textarea defaultValue="Add denominators only after converting to equivalent fractions." aria-label="Teacher note"/></label><div className="button-row"><button className="secondary" onClick={()=>notify("Saved as unable to evaluate")}>Unable to evaluate</button><button data-testid="approve-answer" className="primary" disabled={done} onClick={()=>{setReviewed(Math.min(3,reviewed+1));notify("Answer approved and added to audit history")}}>{done?"Review complete":"Approve & next"}</button></div><p className="audit-note">Model vision-grade-3 · Prompt v12 · Rubric v4 · Teacher approval required</p></aside></div>}
function XRay({notify}:any){const students=["Mira","Kabir","Riya","Aarav","Meera","Ishaan"];return <div className="dashboard-grid"><section className="card span-2"><div className="card-head"><div><p className="eyebrow">Learning X-Ray · Fractions checkpoint</p><h2>Class 6A · Concept evidence</h2></div><span className="status success">Teacher reviewed</span></div><div className="xray-summary"><Metric label="Overall" value="24/40" note="Class average"/><Metric label="Priority concepts" value="2" note="6 students"/><Metric label="Confidence" value="Medium" note="3 evidence points"/><Metric label="Evidence" value="84" note="Approved answers"/></div><div className="heatmap"><div/><b>Equivalent fractions</b><b>Common denominator</b><b>Addition</b><b>Word problems</b>{students.flatMap((s,i)=>[<span key={s}>{s}</span>,...[0,1,2,3].map((_,j)=><button aria-label={`${s} concept ${j+1}`} className={["mastered","developing","gap","review"][(i+j)%4]} key={`${s}${j}`} onClick={()=>notify(`${s}: evidence opened`)}>{[88,72,46,61][(i+j)%4]}%</button>)])}</div><div className="heat-legend"><span><i className="mastered"/>Demonstrated</span><span><i className="developing"/>Developing</span><span><i className="gap"/>Priority gap</span><span><i className="review"/>Review</span></div></section><section className="card"><p className="eyebrow">Priority concept</p><h2>Add fractions with unlike denominators</h2><div className="big-stat">6 <small>students need support</small></div><p>Repeated evidence across 3 approved questions. Students often add both denominators.</p><div className="evidence"><b>Evidence quality</b><p>Medium confidence · 18 answer samples · Rubric v4</p></div><button className="primary" onClick={()=>notify("Intervention planner opened")}>Plan intervention →</button></section><section className="card"><p className="eyebrow">Assessment quality</p><h2>Suitable with limitations</h2><Bar label="Concept coverage" pct={82}/><Bar label="Evidence per concept" pct={68}/><Bar label="Difficulty balance" pct={74}/><p className="insight">This is an assessment evidence score, never a teacher-quality rating.</p><button className="secondary" onClick={()=>notify("Quality details opened")}>Review limitations</button></section></div>}
function Interventions({intervention,setIntervention,notify}:any){return <div className="dashboard-grid"><section className="card"><p className="eyebrow">Recommended plan</p><h2>15-minute guided practice</h2><div className="step-list"><span><i>1</i><b>Worked example</b><small>4 min</small></span><span><i>2</i><b>Pair practice</b><small>5 min</small></span><span><i>3</i><b>Teacher check</b><small>2 min</small></span><span><i>4</i><b>Exit ticket</b><small>4 min</small></span></div><button data-testid="approve-plan" className="primary" onClick={()=>{setIntervention(true);notify("Plan approved for 6 students")}}>{intervention?"Plan approved ✓":"Approve plan"}</button></section><section className="card"><p className="eyebrow">Temporary group · Strengthen</p><h2>Unlike denominators</h2><div className="avatars"><span>MB</span><span>KS</span><span>RM</span><span>AK</span><span>MV</span><span>IP</span></div><p>Concept-specific group for 6 students. Automatically returns for review after follow-up evidence.</p><div className="tag-row"><span>Print available</span><span>15 min</span><span>English</span></div><button className="secondary" onClick={()=>notify("Group members opened")}>Review group</button></section><section className="card span-2"><div className="card-head"><div><p className="eyebrow">Follow-up cycle</p><h2>Measure improvement, not just completion</h2></div><button className="secondary" onClick={()=>notify("New follow-up created")}>＋ Record evidence</button></div><div className="timeline"><div className="done"><i>✓</i><b>Gap approved</b><small>18 Jul</small></div><div className={intervention?"done":"current"}><i>{intervention?"✓":"2"}</i><b>Guided practice</b><small>22 Jul</small></div><div className="current"><i>3</i><b>Parallel exit ticket</b><small>24 Jul</small></div><div><i>4</i><b>Review outcome</b><small>25 Jul</small></div></div></section><section className="card span-2"><div className="card-head"><div><p className="eyebrow">Resource studio</p><h2>Teacher-approved practice</h2></div><span className="status warning">Draft</span></div><div className="resource-preview"><div><b>Adding unlike fractions</b><p>3 worked examples · 6 guided questions · 2 challenge questions</p></div><div className="paper-lines"/></div><div className="button-row"><button className="secondary" onClick={()=>notify("Resource editor opened")}>Edit resource</button><button className="primary" onClick={()=>notify("Resource approved and ready to print")}>Approve resource</button></div></section></div>}
function Reports({notify}:any){return <div className="dashboard-grid"><section className="card span-2"><div className="card-head"><div><p className="eyebrow">Leadership reports</p><h2>Secure, contextual and non-punitive</h2></div><span className="status success">All data aggregated</span></div><div className="report-list"><Report title="July academic improvement" meta="Grades 6–8 · All subjects · 12 pages"/><Report title="Mathematics intervention progress" meta="Grades 6–7 · 8 pages"/><Report title="Assessment quality review" meta="School-wide · 6 pages"/></div></section><section className="card"><p className="eyebrow">Secure sharing</p><h2>Leadership link</h2><label>Expires<select aria-label="Report expiry"><option>In 7 days</option><option>In 30 days</option></select></label><label className="check"><input type="checkbox" defaultChecked/> Require one-time code</label><label className="check"><input type="checkbox"/> Allow download</label><button className="primary" onClick={()=>notify("Secure report link created")}>Create secure link</button></section><section className="card"><p className="eyebrow">Report safeguards</p><h2>Context travels with every insight</h2><ul className="checklist"><li>Data quality and limitations included</li><li>No teacher or student ranking</li><li>Revocable links with open tracking</li><li>Methodology and privacy appendix</li></ul></section></div>}

function PrincipalView({view,notify}:any){if(view==="Reports")return <Reports notify={notify}/>;if(view==="Interventions")return <Interventions intervention={true} setIntervention={()=>{}} notify={notify}/>;if(view==="X-Ray")return <XRay notify={notify}/>;return <><section className="metric-grid"><Metric label="Students analysed" value="1,146" note="91% of active students"/><Metric label="Priority gaps" value="18" note="Across 7 concepts"/><Metric label="Interventions complete" value="76%" note="↑ 8% this month"/><Metric label="Improvement rate" value="64%" note="Comparable evidence"/></section><div className="dashboard-grid"><section className="card span-2"><div className="card-head"><div><p className="eyebrow">Improvement trend</p><h2>Students are moving after support</h2></div><select aria-label="Principal period"><option>Last 8 weeks</option></select></div><div className="chart"><i style={{height:"28%"}}/><i style={{height:"38%"}}/><i style={{height:"45%"}}/><i style={{height:"58%"}}/><i style={{height:"64%"}}/><i style={{height:"72%"}}/><i style={{height:"78%"}}/><i style={{height:"86%"}}/></div></section><section className="card"><p className="eyebrow">Support required</p><h2>3 barriers to resolve</h2><ul className="issue-list"><li><i className="risk"/><div><b>No remedial timetable</b><small>Grade 8 · 4 interventions</small></div></li><li><i className="mid"/><div><b>Resource gap</b><small>Science · 2 concepts</small></div></li><li><i className="mid"/><div><b>Follow-up overdue</b><small>Grade 6 · 18 students</small></div></li></ul><button className="secondary" onClick={()=>notify("Support actions opened")}>Review support actions</button></section><section className="card"><p className="eyebrow">Data confidence</p><h2>Assessment evidence is improving</h2><div className="big-stat">71% <small>diagnostic quality</small></div><Bar label="Question-wise evidence" pct={78}/><Bar label="Follow-up comparability" pct={63}/></section></div></>}
function SchoolAdmin({view,notify,open,invites}:any){
  if(view==="Reports")return <Reports notify={notify}/>;
  return <><section className="metric-grid"><Metric label="Active users" value={String(84+invites.length)} note="72 teachers · 12 leaders"/><Metric label="Students" value="1,248" note="32 sections"/><Metric label="Data imports" value="4" note="1 needs correction"/><Metric label="Retention" value="365d" note="School policy"/></section><div className="dashboard-grid"><section className="card span-2"><div className="card-head"><div><p className="eyebrow">Users & roles</p><h2>School access</h2></div><button data-testid="invite-user" className="primary" onClick={()=>open("invite")}>＋ Invite user</button></div><div className="table"><div className="tr th"><span>Name</span><span>Role</span><span>Scope</span><span>Status</span></div><Row name="Asha Sharma" sub="asha@sunrise.edu" progress="Teacher" action="Grade 6–7 Maths" status="Active"/><Row name="Ravi Menon" sub="ravi@sunrise.edu" progress="Coordinator" action="Mathematics" status="Active"/><Row name="Priya Kapoor" sub="priya@sunrise.edu" progress="Principal" action="School" status="Active"/>{invites.map(x=><Row key={x.email} name={x.name} sub={x.email} progress={x.role} action="Pending assignment" status="Invited"/>)}</div></section><section className="card"><p className="eyebrow">Privacy & retention</p><h2>Student data controls</h2><label className="check"><input type="checkbox" defaultChecked/> Private AI processing only</label><label className="check"><input type="checkbox" defaultChecked/> Support access needs approval</label><label className="check"><input type="checkbox"/> Product-improvement data</label><button className="secondary" onClick={()=>notify("Privacy controls saved")}>Save controls</button></section><section className="card"><p className="eyebrow">School structure</p><h2>2026–27 academic year</h2><div className="big-stat">32 <small>active sections</small></div><div className="tag-row"><span>CBSE</span><span>Grades 1–12</span><span>1 campus</span></div><button className="secondary" onClick={()=>notify("Class manager opened: 32 sections are available")}>Manage classes</button></section></div></>}
function PlatformAdmin({view,notify}:any){if(view==="Reports")return <Reports notify={notify}/>;return <><section className="metric-grid"><Metric label="Active schools" value="56" note="↑ 6 this month"/><Metric label="Monthly users" value="320" note="78% weekly active"/><Metric label="Pages processed" value="124,560" note="99.4% success"/><Metric label="AI cost / assessment" value="₹18.40" note="↓ 7% this month"/></section><div className="dashboard-grid"><section className="card span-2"><div className="card-head"><div><p className="eyebrow">System health</p><h2>All critical services operational</h2></div><span className="status success">Operational</span></div><div className="health-grid">{["API","Upload queue","Vision provider","Report service","Authentication","Database"].map((x,i)=><div key={x}><span className={i===2?"warning-dot":"ok-dot"}/><b>{x}</b><small>{i===2?"Degraded · fallback active":"Operational"}</small></div>)}</div></section><section className="card"><p className="eyebrow">Responsible AI</p><h2>Model routing</h2><div className="route"><span>OCR & handwriting</span><b>Vision Grade 3</b><small>Fallback: Vision Grade 2</small></div><div className="route"><span>Learning analysis</span><b>Reasoning Core 2</b><small>Prompt v12 · Schema v7</small></div><button className="secondary" onClick={()=>notify("AI routing opened")}>Configure routing</button></section><section className="card"><p className="eyebrow">Feature controls</p><h2>Safe rollout</h2>{["AI grading","Regrading","Intervention studio","Teacher badges"].map((x,i)=><label className="switch" key={x}><span>{x}</span><input type="checkbox" defaultChecked={i<3}/><i/></label>)}</section><section className="card span-2"><div className="card-head"><div><p className="eyebrow">AI operations</p><h2>Versioned, validated and auditable</h2></div><button className="primary" onClick={()=>notify("New model configuration started")}>＋ Add model</button></div><div className="table"><div className="tr th"><span>Model</span><span>Capability</span><span>Acceptance</span><span>Status</span></div><Row name="Vision Grade 3" sub="Provider A · India region" progress="OCR + grading" action="91.8%" status="Active"/><Row name="Reasoning Core 2" sub="Provider B · Private endpoint" progress="X-Ray + reports" action="88.4%" status="Active"/><Row name="Resource Draft 4" sub="Provider A · Global" progress="Resources" action="84.2%" status="Restricted"/></div></section></div></>}

function Modal({type,close,notify,uploading,uploaded,startUpload}:any){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal" role="dialog" aria-modal="true" aria-label={type==="upload"?"Upload student work":type==="create"?"Create assessment":"Generate report"}><button className="modal-close" onClick={close} aria-label="Close">×</button><p className="eyebrow">{type==="upload"?"Camera or files":type==="create"?"New learning evidence":"Leadership reporting"}</p><h2>{type==="upload"?"Upload student work":type==="create"?"Create new work":"Generate principal report"}</h2>{type==="upload"?<><div className={`dropzone ${uploaded?"uploaded":""}`}><span>{uploaded?"✓":"↑"}</span><b>{uploaded?"4 pages ready":"Drop PDF or images here"}</b><small>{uploaded?"Quality checked · no duplicates":"PDF, JPG, PNG, HEIC · multiple files supported"}</small></div>{uploading&&<div className="upload-progress"><i/><span>Checking page quality…</span></div>}<button data-testid="start-upload" className="primary full" onClick={uploaded?()=>{notify("Upload sent to background processing");close()}:startUpload} disabled={uploading}>{uploading?"Processing…":uploaded?"Continue to setup":"Choose sample files"}</button></>:type==="create"?<><div className="form-grid"><label>Title<input defaultValue="Fractions follow-up"/></label><label>Activity type<select><option>Follow-up</option><option>Test</option><option>Homework</option></select></label><label>Grade<select><option>Grade 6</option></select></label><label>Section<select><option>A</option></select></label><label>Subject<select><option>Mathematics</option></select></label><label>Maximum marks<input defaultValue="10"/></label></div><button className="primary full" onClick={()=>{notify("Assessment saved as a draft");close()}}>Save & continue</button></>:<><div className="form-grid"><label>Period<select><option>July 2026</option></select></label><label>Scope<select><option>School overview</option></select></label><label>Grades<select><option>Grades 6–8</option></select></label><label>Format<select><option>PDF report</option></select></label></div><div className="insight">Includes executive summary, data quality, priority concepts, interventions, improvement, barriers, recommendations and privacy notes.</div><button className="primary full" onClick={()=>{notify("Report generation started in the background");close()}}>Generate secure report</button></>}</div></div>}

function InteractionModal({type,close,notify,uploading,uploaded,startUpload,addInvite}:any){
  const inputRef=useRef<HTMLInputElement>(null);
  const [files,setFiles]=useState<File[]>([]);
  const choose=(list:FileList|null)=>{const next=Array.from(list||[]);if(!next.length)return;setFiles(next);startUpload();};
  const submit=(e:FormEvent<HTMLFormElement>,message:string)=>{e.preventDefault();notify(message);close();};
  const invite=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const data=new FormData(e.currentTarget);addInvite({name:String(data.get("name")),email:String(data.get("email")),role:String(data.get("role"))});notify(`Invitation sent to ${data.get("email")}`);close();};
  const title=type==="upload"?"Upload student work":type==="create"?"Create new work":type==="invite"?"Invite a school user":"Generate principal report";
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}} onKeyDown={e=>{if(e.key==="Escape")close()}}><div className="modal" role="dialog" aria-modal="true" aria-label={title}><button className="modal-close" onClick={close} aria-label="Close">×</button><p className="eyebrow">{type==="upload"?"Camera or files":type==="create"?"New learning evidence":type==="invite"?"Users & roles":"Leadership reporting"}</p><h2>{title}</h2>
  {type==="upload"?<><input ref={inputRef} className="file-input" type="file" multiple accept=".pdf,image/jpeg,image/png,image/heic" onChange={e=>choose(e.target.files)}/><div className={`dropzone ${uploaded?"uploaded":""}`} role="button" tabIndex={0} onClick={()=>inputRef.current?.click()} onKeyDown={e=>{if(e.key==="Enter"||e.key===" ")inputRef.current?.click()}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files)}}><span>{uploaded?"✓":"↑"}</span><b>{uploaded?`${files.length||1} file${files.length===1?"":"s"} ready`:"Drop PDF or images here"}</b><small>{uploaded?(files.map(f=>f.name).join(", ")||"Quality checked · no duplicates"):"PDF, JPG, PNG, HEIC · multiple files supported"}</small></div>{uploading&&<div className="upload-progress"><i/><span>Checking page quality…</span></div>}<button data-testid="start-upload" className="primary full" onClick={uploaded?()=>{notify(`${files.length||1} file${files.length===1?"":"s"} sent to background processing`);close()}:()=>inputRef.current?.click()} disabled={uploading}>{uploading?"Processing…":uploaded?"Continue to setup":"Browse / Choose files"}</button></>
  :type==="invite"?<form onSubmit={invite}><label>Teacher name<input name="name" required autoFocus placeholder="e.g. Neha Verma"/></label><label>Email ID<input name="email" type="email" required placeholder="teacher@school.edu"/></label><div className="form-grid"><label>Role<select name="role"><option>Teacher</option><option>Coordinator</option><option>Principal</option><option>School admin</option></select></label><label>Access scope<select name="scope"><option>Assigned classes</option><option>Department</option><option>Whole school</option></select></label></div><button data-testid="send-invite" className="primary full" type="submit">Send invitation</button></form>
  :type==="create"?<form onSubmit={e=>submit(e,"Assessment saved as a draft")}><div className="form-grid"><label>Title<input name="title" required defaultValue="Fractions follow-up"/></label><label>Activity type<select name="type"><option>Follow-up</option><option>Test</option><option>Homework</option></select></label><label>Grade<select name="grade"><option>Grade 6</option><option>Grade 7</option><option>Grade 8</option></select></label><label>Section<select name="section"><option>A</option><option>B</option></select></label><label>Subject<select name="subject"><option>Mathematics</option><option>Science</option><option>English</option></select></label><label>Maximum marks<input name="marks" type="number" min="1" required defaultValue="10"/></label></div><button className="primary full" type="submit">Save & continue</button></form>
  :<form onSubmit={e=>submit(e,"Report generation started in the background")}><div className="form-grid"><label>Period<select name="period"><option>July 2026</option><option>Term 1</option><option>Academic year</option></select></label><label>Scope<select name="scope"><option>School overview</option><option>Mathematics</option><option>Interventions</option></select></label><label>Grades<select name="grades"><option>Grades 6–8</option><option>All grades</option></select></label><label>Format<select name="format"><option>PDF report</option><option>Spreadsheet</option></select></label></div><div className="insight">Includes executive summary, data quality, priority concepts, interventions, improvement, barriers, recommendations and privacy notes.</div><button className="primary full" type="submit">Generate secure report</button></form>}</div></div>;
}

function Metric({label,value,note,tone,action}:any){const content=<><span>{label}</span><b>{value}</b><small>{note}</small></>;return action?<button className={`metric ${tone||""}`} onClick={action}>{content}</button>:<article className={`metric ${tone||""}`}>{content}</article>}
function Row({name,sub,progress,action,status}:any){return <div className="tr"><span><b>{name}</b><small>{sub}</small></span><span>{progress}</span><span>{action}</span><span><i className={`status ${status==="Active"||status==="Ready"?"success":status==="Processing"?"neutral":"warning"}`}>{status}</i></span></div>}
function Bar({label,pct}:any){return <div className="bar"><span><b>{label}</b><small>{pct}%</small></span><i><em style={{width:`${pct}%`}}/></i></div>}
function WorkCard({title,meta,pct,state,onClick}:any){return <button className="work-card" onClick={onClick||(()=>window.alert(`${title}\n${meta}\n${state}`))}><div className="mini-paper"><i/><i/><i/></div><b>{title}</b><small>{meta}</small><Bar label="Progress" pct={pct}/><span>{state} →</span></button>}
function Report({title,meta,onClick}:any){return <button onClick={onClick||(()=>window.alert(`${title}\n${meta}\nReport preview is ready.`))}><span className="report-icon">▥</span><div><b>{title}</b><small>{meta}</small></div><span className="status success">Ready</span><i>•••</i></button>}
