"use client";
import {useEffect,useRef,useState} from "react";
type Row={learnerId:string;note:string;confidence:string;performanceLevelId:string;status?:string};
const validGrade=(value:unknown)=>value!==null&&value!==undefined&&value!==""&&Number.isInteger(Number(value));
export default function HpcBulkObservations({request}:{request:typeof fetch}){
 const [learners,setLearners]=useState<any[]>([]),[activities,setActivities]=useState<any[]>([]),[levels,setLevels]=useState<any[]>([]),[grade,setGrade]=useState(""),[activity,setActivity]=useState(""),[rows,setRows]=useState<Row[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);const batch=useRef("");
 useEffect(()=>{void Promise.all([request("/api/hpc/learners"),request("/api/hpc/activities"),request("/api/hpc/foundation")]).then(async rs=>{const ps=await Promise.all(rs.map(r=>r.json()));if(rs.some(r=>!r.ok))throw Error("Unable to load bulk observation choices.");setLearners(ps[0].learners||[]);setActivities(ps[1].activities||[]);setLevels(ps[2].framework?.performanceLevels||[])}).catch(e=>setError(e.message))},[]);
 const change=(id:string,patch:Partial<Row>)=>setRows(current=>current.map(row=>row.learnerId===id?{...row,...patch}:row));
 const save=async()=>{setBusy(true);setError("");if(!batch.current)batch.current=crypto.randomUUID();try{const r=await request("/api/hpc/observations/bulk",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({batchId:batch.current,activityId:activity,entries:rows.filter(row=>row.status!=="Saved")})});const p=await r.json();if(!r.ok)throw Error(p.error||"Unable to save observations.");setRows(current=>current.map(row=>{const result=p.results.find((x:any)=>x.learnerId===row.learnerId);return result?{...row,status:result.ok?"Saved":result.error}:row}))}catch(e){setError(e instanceof Error?e.message:"Connection failed. Retry this batch; saved observations will not be duplicated.")}finally{setBusy(false)}};
 const selected=new Set(rows.map(r=>r.learnerId));
 return <section className="card span-2"><p className="eyebrow">HPC · teacher capture</p><h2>Bulk teacher observations</h2><p>Select up to 50 learners. Each keeps an individual observation, confidence and optional performance level. All entries require moderation.</p><div className="form-grid"><label>Filter class<select value={grade} onChange={e=>setGrade(e.target.value)}><option value="">All classes</option>{Array.from(new Set(learners.filter(l=>validGrade(l.grade)).map(l=>String(l.grade)))).sort((a,b)=>Number(a)-Number(b)).map(g=><option key={g}>{g}</option>)}</select></label><label>Activity<select value={activity} disabled={!!batch.current} onChange={e=>setActivity(e.target.value)}><option value="">No activity</option>{activities.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label></div><div className="hpc-prompt-grid">{learners.filter(l=>!grade||String(l.grade)===grade).map(l=><label key={l.id} className="check"><input type="checkbox" checked={selected.has(l.id)} disabled={busy||!!batch.current||!validGrade(l.grade)||(!selected.has(l.id)&&rows.length>=50)} onChange={e=>setRows(current=>e.target.checked?[...current,{learnerId:l.id,note:"",confidence:"medium",performanceLevelId:""}]:current.filter(r=>r.learnerId!==l.id))}/>{l.students?.name} · {validGrade(l.grade)?`Grade ${l.grade}`:"Grade not set"} · {l.academic_year}</label>)}</div>{rows.map(row=><fieldset key={row.learnerId} className="hpc-subform" disabled={busy||row.status==="Saved"}><legend>{learners.find(l=>l.id===row.learnerId)?.students?.name}</legend><label>Individual observation<textarea value={row.note} onChange={e=>change(row.learnerId,{note:e.target.value})}/></label><div className="form-grid"><label>Confidence<select value={row.confidence} onChange={e=>change(row.learnerId,{confidence:e.target.value})}>{["low","medium","high"].map(v=><option key={v}>{v}</option>)}</select></label><label>Performance level<select value={row.performanceLevelId} disabled={!(()=>{const raw=learners.find(l=>l.id===row.learnerId)?.grade;if(!validGrade(raw))return false;const g=Number(raw);return g>=6&&g<=8})()} onChange={e=>change(row.learnerId,{performanceLevelId:e.target.value})}><option value="">Not selected</option>{levels.map(l=><option key={l.id} value={l.id}>{l.label}</option>)}</select></label></div>{row.status&&<p role="status">{row.status}</p>}</fieldset>)}{error&&<p className="form-error" role="alert">{error}</p>}<div className="button-row"><button className="primary" disabled={busy||!rows.length||rows.every(r=>r.status==="Saved")||rows.some(r=>r.note.trim().length<2)} onClick={()=>void save()}>{busy?"Saving…":"Save unsaved observations"}</button><button className="secondary" disabled={busy} onClick={()=>{batch.current="";setRows([]);setError("")}}>Start new batch</button></div></section>;
}
