# Generated by Django 5.2.17 on 2026-09-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('name', models.TextField()),
                ('role', models.TextField(choices=[('SchoolAdmin', 'SchoolAdmin'), ('Teacher', 'Teacher'), ('Parent', 'Parent')])),
                ('credits', models.IntegerField()),
                ('status', models.TextField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Expired', 'Expired'), ('Revoked', 'Revoked')])),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'invitations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('role', models.TextField(choices=[('SuperAdmin', 'SuperAdmin'), ('SchoolAdmin', 'SchoolAdmin'), ('Teacher', 'Teacher'), ('Parent', 'Parent')])),
                ('phone', models.TextField(blank=True, null=True)),
                ('status', models.TextField()),
                ('profile_json', models.JSONField()),
                ('total_credits', models.IntegerField()),
                ('used_credits', models.IntegerField()),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
