# Generated by Django 5.2.17 on 2026-09-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentInviteCode',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('relationship', models.TextField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Guardian', 'Guardian')])),
                ('max_uses', models.IntegerField()),
                ('used_count', models.IntegerField()),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'parent_invite_codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParentStudentLink',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('relationship', models.TextField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Guardian', 'Guardian')])),
                ('status', models.TextField(choices=[('active', 'Active'), ('revoked', 'Revoked')])),
                ('linked_via', models.TextField(choices=[('invite_code', 'Invite code'), ('admin', 'Created by an admin')])),
                ('created_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parent_student_links',
                'managed': False,
            },
        ),
    ]
